# action.yaml
name: 'mdBook to JSON file'
description: 'A GitHub Action that takes an mdBook url input and generates an indexed JSON file of all pages.'
inputs:
  mbBook_url:
    description: 'Enter url to mdBook based wiki'
    required: true
    default: "https://rust-lang.github.io/mdBook/"
  output_file:
    description: 'Enter desired file path'
    required: false
branding:
  icon: 'file-text'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependency "requests"
      run: pip install -r requests
      shell: bash
    - name: Install Dependencies "beautifulsoup4"
      run: pip install -r beautifulsoup4
      shell: bash
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Index mdBook to JSON
      id: index_task
      run: python src/generate_index_JSON.py ${{ inputs.mbBook_url }} json_index/${{ inputs.output_file }}
      shell: bash
