# action.yaml
name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
inputs:
  wiki_url:
    description: 'Enter url to mdBook based wiki'
    required: true
    default: "https://rust-lang.github.io/mdBook/"
  output_file:
    description: 'Enter desired file path'
    required: false
  branch_name:
    description: 'Name of the branch to push the index to'
    required: true
    default: json_index
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Index mdBook to JSON
      id: index_task
      run: python src/generate_index_JSON.py ${{ inputs.wiki_url }} ./json_index/${{ inputs.output_file }}
      shell: bash
    - name: Deploy Data
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./json_index
            publish_branch: ${{inputs.branch_name}}