name: Test Action
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    get-num-square:
      runs-on: ubuntu-latest
      name: Testing functionality
      steps:
        - name: Index mdBook 
          id: mdBook_site_to_JSON
          uses: ./ # Uses an action in the root directory
          # or use a released GitHub Action
          # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
          with:
            wiki_url: https://wiki.wabbajack.org/
            output_file: example_output.json
